### ISSUE TITLE
Option to exclude certain products/categories

### ISSUE THREAD

**Issue by mindctrl** [easydigitaldownloads/edd-rcp-member-discounts#5]
Customer requested ability to exclude certain products from the automatic discounts. Is this something we'd want to do?

**Comment by pippinsplugins** [comment]
It definitely has merit. Let's see if we get another request or two for it
before devoting extra time though.

**Comment by mindctrl** [comment]
Another request for this.

**Comment by mindctrl** [comment]
Got a request to exclude categories.

**Comment by mindctrl** [comment]
Got a good start to this in `issue/5`. Not sure if single product needs to be support with download categories being supported. Only partial code here for that, which could easily be removed. Not sure where a checkbox exclusion fits in semantically on the post edit screen.

**Comment by pippinsplugins** [comment]
I like the idea of supporting product exclusions too. That way admins are not forced to use categories, which they may not want to do.

**Comment by mindctrl** [comment]
Good point. Added post level support in the latest commit.

**Comment by mindctrl** [comment]
PR sent.

I also shifted a few things around to bail early and reduce the number of queries that run in `apply_discounts` if certain conditions aren't met.

**Comment by pippinsplugins** [comment]
Works perfectly.
